/** Curated icon set offered to projects and tasks. Keys are stored in the database, so never rename one. */
import {
  BarChart3,
  Blocks,
  BookOpen,
  Bot,
  Braces,
  Briefcase,
  Bug,
  Camera,
  Cloud,
  Code,
  Coffee,
  Component,
  Cpu,
  CreditCard,
  Database,
  FileText,
  FlaskConical,
  Gamepad2,
  Globe,
  GraduationCap,
  Image,
  Key,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  Mail,
  Map,
  MessageCircle,
  Monitor,
  Music,
  Network,
  Newspaper,
  Package,
  Palette,
  PenTool,
  Plane,
  Puzzle,
  Rocket,
  Server,
  Shield,
  ShoppingCart,
  Smartphone,
  Store,
  Target,
  Terminal,
  Trophy,
  Users,
  Video,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

export const ENTITY_ICONS = {
  rocket: Rocket,
  globe: Globe,
  code: Code,
  terminal: Terminal,
  braces: Braces,
  database: Database,
  server: Server,
  cloud: Cloud,
  cpu: Cpu,
  network: Network,
  smartphone: Smartphone,
  monitor: Monitor,
  layout: LayoutDashboard,
  component: Component,
  blocks: Blocks,
  palette: Palette,
  penTool: PenTool,
  image: Image,
  video: Video,
  music: Music,
  camera: Camera,
  fileText: FileText,
  bookOpen: BookOpen,
  newspaper: Newspaper,
  graduationCap: GraduationCap,
  briefcase: Briefcase,
  store: Store,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  wallet: Wallet,
  chart: BarChart3,
  mail: Mail,
  messageCircle: MessageCircle,
  users: Users,
  bot: Bot,
  bug: Bug,
  wrench: Wrench,
  shield: Shield,
  key: Key,
  package: Package,
  puzzle: Puzzle,
  gamepad: Gamepad2,
  trophy: Trophy,
  map: Map,
  plane: Plane,
  leaf: Leaf,
  coffee: Coffee,
  lightbulb: Lightbulb,
  flask: FlaskConical,
  target: Target,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ENTITY_ICONS

export const ICON_NAMES = Object.keys(ENTITY_ICONS) as IconName[]

/** Lookup by stored key: unknown keys (written by another build) resolve to `undefined`. */
export const ICON_REGISTRY: Record<string, LucideIcon | undefined> = ENTITY_ICONS
